name: laravel-git-action-test
services:
    laravel.test:
        container_name: laravel.test
        build:
            context: docker/8.4/dev
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '2222:22'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            SSH_USER: '${SSH_USER}'
            SSH_PASSWORD: '${SSH_PASSWORD}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_NAME: 'mariadb'
            SUPERVISOR_PHP_COMMAND: '${SUPERVISOR_PHP_COMMAND}'
        volumes:
            - '.:/var/www/html'
            - laravel_test_nvm_cache:${NVM_CACHE}
            - laravel_test_cache:${CACHE}
            - laravel_test_local:${LOCAL}
            - laravel_test_config:${CONFIG}
            - laravel_test_vscode_server:${VSCODE_SERVER_CACHE}
            - laravel_test_global_composer:${GLOBAL_COMPOSER_DIR}
        networks:
            - sail
        depends_on:
            - redis
            - mailpit
            - selenium
            - mariadb
            - minio

    redis:
        container_name: redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        container_name: mailpit
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    selenium:
        container_name: selenium
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail

    mariadb:
        container_name: mariadb
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MARIADB_BIND_ADDRESS: 0.0.0.0
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './docker/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s

    minio:
        container_name: minio
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: sail
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'sail-minio:/data'
        networks:
            - sail
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - mc
                - ready
                - local
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-mariadb:
        driver: local
    sail-mysql:
        driver: local
    sail-minio:
        driver: local
    laravel_test_nvm_cache:
        driver: local
    laravel_test_cache:
        driver: local
    laravel_test_local:
        driver: local
    laravel_test_config:
        driver: local
    laravel_test_vscode_server:
        driver: local
    laravel_test_global_composer:
        driver: local
