name: Laravel CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Install dependencies
      run: |
        docker exec laravel.test composer install
        docker exec laravel.test npm install
        docker exec laravel.test npm run build

    - name: Set environment variables
      run: docker exec laravel.test cp .env.test .env

    - name: Generate application key
      run: docker exec laravel.test php artisan key:generate

    - name: Run migrations
      run: docker exec laravel.test php artisan migrate --force

    - name: Run tests
      run: docker exec laravel.test php artisan test

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: |
        echo "Deployment script or command goes here."
