name: Laravel CI with Custom PHP 8.4 Extensions

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      mailpit:
        image: axllent/mailpit:latest
        ports:
          - 1025:1025
          - 8025:8025

      selenium:
        image: selenium/standalone-chromium
        ports:
          - 4444:4444

      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: sail
          MINIO_ROOT_PASSWORD: password
        ports:
          - 9000:9000
          - 8900:8900
        options: >-
          --health-cmd="mc alias set local http://localhost:9000 sail password && mc admin info local"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: >
          cli, dev, gd, curl, imap, mysql, mbstring, xml, zip,
          bcmath, soap, intl, readline, ldap, msgpack,
          igbinary, redis, memcached, pcov, imagick
        tools: composer
        coverage: none

    - name: Install Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        npm install
        npm run build

    - name: Set up Environment Variables
      run: cp .env.test .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
