name: Laravel CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy .env.test to .env
      run: cp .env.test .env

    - name: Verify Docker Compose
      run: docker compose version

    - name: Set up Docker Compose
      run: docker compose up -d

    - name: Install dependencies
      run: |
        docker exec laravel.test composer install
        docker exec laravel.test npm install
        docker exec laravel.test npm run build

    - name: Generate application key
      run: docker exec laravel.test php artisan key:generate

    - name: Run migrations
      run: docker exec laravel.test php artisan migrate --force

    - name: Run tests
      run: docker exec laravel.test php artisan test

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: |
        echo "Deployment script or command goes here."
